### PR TITLE
running process.py to update population.csv

### PR DESCRIPTION
**Pull request by bgrayburn**
running process.py to update population.csv

### CODE REVIEW

**Comment by rufuspollock** [comment]
Great to have this pull request - thank-you.

Any idea why so many rows have changed? I would imagine that it would have been fairly minimal ...

**Comment by rufuspollock** [comment]
@bgrayburn do you want to try the diff trick on this data?

**Comment by bgrayburn** [comment]
@rgrp same deal as GDP, values are different

here's a sample:

```
Argentina,ARG,1991,[-33093579^M-]{+33075194^M+}
Argentina,ARG,1992,[-33540023^M-]{+33520803^M+}
Argentina,ARG,1993,[-33982035^M-]{+33961947^M+}
Argentina,ARG,1994,[-34420352^M-]{+34399343^M+}
Argentina,ARG,1995,[-34855160^M-]{+34833168^M+}
Argentina,ARG,1996,[-35287113^M-]{+35264070^M+}
Argentina,ARG,1997,[-35714929^M-]{+35690778^M+}
Argentina,ARG,1998,[-36134642^M-]{+36109342^M+}
Argentina,ARG,1999,[-36541029^M-]{+36514558^M+}
Argentina,ARG,2000,[-36930709^M-]{+36903067^M+}
Argentina,ARG,2001,[-37302116^M-]{+37273361^M+}
Argentina,ARG,2002,[-37657340^M-]{+37627545^M+}
Argentina,ARG,2003,[-38001251^M-]{+37970411^M+}
Argentina,ARG,2004,[-38340778^M-]{+38308779^M+}
Argentina,ARG,2005,[-38681174^M-]{+38647854^M+}
Argentina,ARG,2006,[-39023850^M-]{+38988923^M+}
Argentina,ARG,2007,[-39368066^M-]{+39331357^M+}
Argentina,ARG,2008,[-39714298^M-]{+39676083^M+}
Argentina,ARG,2009,[-40062470^M-]{+40023641^M+}
Argentina,ARG,2010,[-40412000^M-]{+40374224^M+}
```

if I hear back from worldbank regarding gdp, I'll follow up asking about this.

As for the details of the commit, same as GDP, new dataset is 1960-2014, old dataset is 1960-2010

**Comment by bgrayburn** [comment]
Thanks Rufus for this and the gdp merge!

**Pull request merged**
